#!/bin/sh

sudo apt-get install g++ make gawk

wget http://ftpmirror.gnu.org/binutils/binutils-2.24.tar.gz  
wget http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.gz  
wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.17.2.tar.xz  
wget http://ftpmirror.gnu.org/glibc/glibc-2.20.tar.xz  
wget http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.xz  
wget http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.xz  
wget http://ftpmirror.gnu.org/mpc/mpc-1.0.2.tar.gz  
wget ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.12.2.tar.bz2  
wget ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.1.tar.gz

for f in *.tar*; do tar xf $f; done

cd gcc-4.9.2  
ln -s ../mpfr-3.1.2 mpfr  
ln -s ../gmp-6.0.0 gmp  
ln -s ../mpc-1.0.2 mpc  
ln -s ../isl-0.12.2 isl  
ln -s ../cloog-0.18.1 cloog  
cd ..

sudo mkdir -p /opt/cross  
sudo chown $(whoami) /opt/cross

export PATH=/opt/cross/bin:$PATH

PLATFORMS=( "arm-none-linux-gnueabi" "mips-linux" )  
ARCHS=( "arm" "mips" )

for (( i = 0 ; i < ${#PLATFORMS[@]} ; i++ )) ; do  
    PLATFORM=${PLATFORMS[$i]}
    ARCH=${ARCHS[$i]}

    mkdir -p build-binutils
    cd build-binutils
    ../binutils-2.24/configure --prefix=/opt/cross --target=${PLATFORM} --disable-multilib --disable-werror
    make && make install && cd ..

    cd linux-3.17.2
    make ARCH=${ARCH} INSTALL_HDR_PATH=/opt/cross/${PLATFORM} headers_install
    cd ..

    mkdir -p build-gcc
    cd build-gcc
    ../gcc-4.9.2/configure --prefix=/opt/cross --target=${PLATFORM} --enable-languages=c,c++ --disable-multilib
    make all-gcc && make install-gcc && cd ..

    mkdir -p build-glibc
    cd build-glibc
    ../glibc-2.20/configure --prefix=/opt/cross/${PLATFORM} --build=$MACHTYPE --host=${PLATFORM} --target=${PLATFORM} --with-headers=/opt/cross/${PLATFORM}/include --disable-multilib libc_cv_forced_unwind=yes
    make install-bootstrap-headers=yes install-headers
    make csu/subdir_lib
    install csu/crt1.o csu/crti.o csu/crtn.o /opt/cross/${PLATFORM}/lib
    ${PLATFORM}-gcc -nostdlib -nostartfiles -shared -x c /dev/null -o /opt/cross/${PLATFORM}/lib/libc.so
    touch /opt/cross/${PLATFORM}/include/gnu/stubs.h
    cd ..

    cd build-gcc
    make all-target-libgcc && make install-target-libgcc && cd ..

    cd build-glibc
    make && make install && cd ..

    cd build-gcc
    make && make install && cd ..

    rm -rf build-gcc build-binutils build-glibc
done  
